stages: [test, analysis, build, deploy]

include:
  - component: $CI_SERVER_FQDN/devops/cicd/gitlab-ci-toolkit/nextjs-unit-tests@1.8.0
    inputs:
      artifacts:
        - coverage
        - gl-codequality.json
  - component: $CI_SERVER_FQDN/devops/cicd/gitlab-ci-toolkit/nextjs-sonarqube-analysis@1.8.0
    inputs:
      dependencies:
        - nextjs-unit-tests
  - component: $CI_SERVER_FQDN/devops/cicd/gitlab-ci-toolkit/nextjs-build-docker-image@1.8.0
    inputs:
      dependencies:
        - nextjs-sonarqube-analysis

deploy:
  image:
    name: bitnami/kubectl:1.30.2
    entrypoint: [ '' ]
  stage: deploy
  needs:
    - nextjs-build-docker-image
  only:
    - dev
  before_script:
    - echo "$KUBE_CONFIG_DEV" | base64 -d > kubeconfig
  script:
    - kubectl --kubeconfig kubeconfig rollout restart deployment.apps/swarm-console -n swarm-dev