import { IMAGE_FLAG_OF_EUROPE, IMAGE_LYCEE_CONNECTE, IMAGE_NOUVELLE_AQUITAINE } from "@/core/const";

export const headerImages = [IMAGE_NOUVELLE_AQUITAINE, IMAGE_LYCEE_CONNECTE, IMAGE_FLAG_OF_EUROPE];
