export enum CURRENTTAB_STATE {
  MAIN = "main",
  STATS = "stats",
}
export enum SERVICE_TYPE {
  PRESTASHOP = "PRESTASHOP",
  WORDPRESS = "WORDPRESS",
}
export enum SERVICE_STATUS {
  SCHEDULED = "SCHEDULED",
  IN_PROGRESS = "IN_PROGRESS",
  DEPLOYED = "DEPLOYED",
  DELETION_SCHEDULED = "DELETION_SCHEDULED",
  DELETION_IN_PROGRESS = "DELETION_IN_PROGRESS",
  RESET_SCHEDULED = "RESET_SCHEDULED",
  RESET_IN_PROGRESS = "RESET_IN_PROGRESS",
  DEACTIVATION_SCHEDULED = "DEACTIVATION_SCHEDULED",
  DISABLED = "DISABLED",
  REACTIVATION_SCHEDULED = "REACTIVATION_SCHEDULED",
}

export enum SERVICE_STATE_DISPLAY {
  ACTIVE = "ACTIVE",
  WAITING = "WAITING",
  INACTIVE = "INACTIVE",
}

export enum COLUMN_ID {
  SELECT = "SELECT",
  NAME = "NAME",
  CLASS = "CLASS",
  ETAB = "ETAB",
  SERVICES = "SERVICES",
  STATUS = "STATUS",
  DELETION_DATE = "DELETION_DATE",
}

export enum ORDER_TYPE {
  ASC = "ASC",
  DESC = "DESC",
}

export enum MODAL_TYPE {
  CREATE = "createServices",
  DELETE = "deleteServices",
  CONFIRMATION = "confirmation",
  SEND = "sendServices",
  TOGGLE_STATUS = "toggleStatusServices",
  REINIT = "reinitServices",
  UPDATE = "updateServices",
}

export enum PATH {
  MAIN = "/",
  STATS = "/stats",
}
